# Generated by Django 2.0 on 2018-01-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0004_auto_20171224_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='category',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
