# Generated by Django 2.0 on 2018-02-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0006_auto_20180212_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteriascore',
            name='score_mode',
        ),
        migrations.AddField(
            model_name='criteria',
            name='score_mode',
            field=models.CharField(choices=[('0', 'Only Use Children'), ('1', 'Include Self Score')], default='0', max_length=1),
        ),
    ]
