# Generated by Django 2.0 on 2018-02-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0005_criteria_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria',
            name='category',
        ),
        migrations.AddField(
            model_name='criteriascore',
            name='score_mode',
            field=models.CharField(choices=[('0', 'From Children'), ('1', 'No Children'), ('2', 'User Both')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='benefits',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='hurts',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='criteriascore',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
