# Generated by Django 2.0 on 2018-02-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0007_auto_20180220_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='inspiredFrom',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
