# Generated by Django 2.0 on 2017-12-25 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0002_tool_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('pre', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how', models.TextField()),
                ('num_of_steps', models.IntegerField(default=0)),
                ('ease_score', models.IntegerField(default=0)),
                ('quality_score', models.IntegerField(default=0)),
                ('pre', models.TextField(blank=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.Tool')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='taskscore',
            unique_together={('task', 'tool')},
        ),
    ]
