# Generated by Django 2.0 on 2017-12-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('tools', '0002_tool_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='tasks_scores',
            field=models.ManyToManyField(through='tasks.TaskScore', to='tasks.Task'),
        ),
    ]
